language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_12f9df099616_key -iv $encrypted_12f9df099616_iv
  -in price-the-vintage-firebase-adminsdk.json.enc -out price-the-vintage-firebase-adminsdk.json
  -d
