language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_77ecc3c28ae8_key -iv $encrypted_77ecc3c28ae8_iv
  -in lib/config/ucd-library-apps.json.enc -out lib/config/ucd-library-apps-firebase-adminsdk-vrtjx-8eef33af91.json
  -d
