language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_12f9df099616_key -iv $encrypted_12f9df099616_iv
  -in lib/config/price-the-vintage-firebase-adminsdk.json.enc -out lib/config/price-the-vintage-firebase-adminsdk.json
  -d
